# WORK IN PROGRESS
services:
  ollama-tg:
    build:
      context: .
      dockerfile: Dockerfile.ollama-tg
    container_name: ollama-tg
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ollama-tg:/code/  # Mounting a volume for SQLite database

  ollama-api:
    image: ollama/ollama:latest
    container_name: ollama-server
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: on-failure

  faster-whisper:
    build:
      context: .
      dockerfile: Dockerfile.faster-whisper
    environment:
      - MODEL_SIZE=large-v3
      - DEVICE=cuda  # cpu / cuda
      - COMPUTE_TYPE=int8
    volumes:
      - whisper-models:/root/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: on-failure

  piper-tts:
    build:
      context: .
      dockerfile: Dockerfile.piper-tts
    container_name: piper-tts
    environment:
      - PIPER_VOICE=en_US-ryan-high
      - PIPER_DATA_DIR=/app/voices
    volumes:
      - tts-voices:/app/voices
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama-tg:
  whisper-models:
  tts-voices:
