# WORK IN PROGRESS
services:
  ollama-tg:
    build: .
    container_name: ollama-tg
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ollama-tg:/code/  # Mounting a volume for SQLite database

  ollama-api:
    image: ollama/ollama:latest
    container_name: ollama-server
    volumes:
      - ./ollama:/root/.ollama

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    restart: always
    ports:
      - '11440:11434'
volumes:
  ollama-tg: