FROM python:3.12-alpine

ARG APPHOMEDIR=code
ARG USERNAME=user
ARG USER_UID=1001
ARG USER_GID=1001
ARG PYTHONPATH_=${APPHOMEDIR}

WORKDIR /${APPHOMEDIR}

# Install dependency packages, upgrade pip and then install requirements
RUN \
    apk add --no-cache gcc g++ \
    && python -m pip install --upgrade pip \
    && pip install --no-cache-dir \
        python-dotenv==1.1.0 \
        aiogram==3.19.0 \
        ollama==0.4.7 \
        telegramify-markdown==0.5.0 \
        typing \
        requests==2.32.3 \
    && apk del --no-cache gcc g++

COPY ./bot /${APPHOMEDIR}

# Configure app home directory
RUN \
    addgroup -g "$USER_GID" "$USERNAME" \
    && adduser --disabled-password -u "$USER_UID" -G "$USERNAME" -h /"$APPHOMEDIR" "$USERNAME" \
    && mkdir -p /${APPHOMEDIR}/data \
    && chown "$USERNAME:$USERNAME" -R /"$APPHOMEDIR"

USER ${USERNAME}

CMD ["python3", "-u", "run.py"]
