services:
  ollama-tg:
    build:
      context: .
      dockerfile: Dockerfile.ollama-tg
    container_name: ollama-tg
    volumes:
      - ollama-tg:/code/data  # Mounting a volume for SQLite database
    restart: on-failure
    env_file:
      - ./.env

  ollama-api:
    image: ollama/ollama:latest
    container_name: ollama-server
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: on-failure

  faster-whisper:
    build:
      context: .
      dockerfile: Dockerfile.faster-whisper-stt
    volumes:
      - whisper:/root/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: on-failure
    env_file:
      - ./.env

  # piper-tts:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.piper-tts
  #   container_name: piper-tts
  #   environment:
  #     - PIPER_DATA_DIR=/app/voices
  #   volumes:
  #     - piper:/app/voices
  #   restart: on-failure
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   env_file:
  #     - ./.env

  kokoro-tts:
    build:
      context: .
      dockerfile: Dockerfile.kokoro-tts
    container_name: kokoro-tts
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - kokoro:/root/.cache/huggingface/hub
    env_file:
      - ./.env
  
volumes:
  ollama-tg:
  whisper:
  # piper:
  kokoro:
